### PR TITLE
Fixed tests

### PR DESCRIPTION
**Pull request by noisecapella**

### CODE REVIEW

**Comment by justinabrahms** [comment]
Can we un-swap the "views_test" to "test_views"?  The former allows us to view the code and the tests one after another during code review.

**Comment by justinabrahms** [comment]
:+1: beyond test names.

**Comment by noisecapella** [comment]
I made that change because I couldn't figure out how to get the tests to run with the other name. Would you mind investigating?

**Comment by justinabrahms** [comment]
It "just worked". I undid the rename. 
just-works

**Pull request merged**
